# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from StorageManager.idl.

use strict;

package Raritan::RPC::webcam::StorageManager_1_0_2::ImageUploadStartedEvent;

use constant typeId => "webcam.StorageManager_1_0_2.ImageUploadStartedEvent:1.0.0";
use Raritan::RPC::event::UserEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'webcam'} = Raritan::RPC::ObjectCodec::encode($in->{'webcam'});
    $encoded->{'folderUrl'} = "$in->{'folderUrl'}";
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'webcam'} = Raritan::RPC::ObjectCodec::decode($agent, $in->{'webcam'}, 'webcam.Webcam');
    $decoded->{'folderUrl'} = $in->{'folderUrl'};
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('webcam.StorageManager_1_0_2.ImageUploadStartedEvent', 1, 0, 0, 'Raritan::RPC::webcam::StorageManager_1_0_2::ImageUploadStartedEvent');
1;
