# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Controller.idl.

use strict;

package Raritan::RPC::pdumodel::Controller_2_0_1::Events;

use constant EVT_KEY_STATUS_CHANGED => 0;

1;
