# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from CardReader.idl.

use strict;

package Raritan::RPC::smartcard::CardReader::CardRemovedEvent;

use constant typeId => "smartcard.CardReader.CardRemovedEvent:1.0.0";
use Raritan::RPC::smartcard::CardReader::CardEvent;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::smartcard::CardReader::CardEvent::encode($in);
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::smartcard::CardReader::CardEvent::decode($agent, $in);
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('smartcard.CardReader.CardRemovedEvent', 1, 0, 0, 'Raritan::RPC::smartcard::CardReader::CardRemovedEvent');
1;
