# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from AssetStripConfig.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStripConfig_1_0_1::LEDOperationMode;

use constant LED_OPERATION_MANUAL => 0;
use constant LED_OPERATION_AUTO => 1;

1;
