# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from PowerMeter.idl.

use strict;

package Raritan::RPC::pdumodel::PowerMeter::Settings;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'name'} = "$in->{'name'}";
    $encoded->{'currentRating'} = 1 * $in->{'currentRating'};
    $encoded->{'phaseCtRating'} = 1 * $in->{'phaseCtRating'};
    $encoded->{'neutralCtRating'} = 1 * $in->{'neutralCtRating'};
    $encoded->{'earthCtRating'} = 1 * $in->{'earthCtRating'};
    $encoded->{'modbusUnitAddress'} = 1 * $in->{'modbusUnitAddress'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'name'} = $in->{'name'};
    $decoded->{'currentRating'} = $in->{'currentRating'};
    $decoded->{'phaseCtRating'} = $in->{'phaseCtRating'};
    $decoded->{'neutralCtRating'} = $in->{'neutralCtRating'};
    $decoded->{'earthCtRating'} = $in->{'earthCtRating'};
    $decoded->{'modbusUnitAddress'} = $in->{'modbusUnitAddress'};
    return $decoded;
}

1;
