// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright 2020 Raritan Inc. All rights reserved.
//
// This file was generated by IdlC from TypeBResidualCurrentNumericSensor.idl.

using System;
using System.Linq;
using LightJson;
using Com.Raritan.Idl;
using Com.Raritan.JsonRpc;
using Com.Raritan.Util;

#pragma warning disable 0108, 0219, 0414, 1591

namespace Com.Raritan.Idl.pdumodel {
  public class TypeBResidualCurrentNumericSensor : Com.Raritan.Idl.sensors.NumericSensor_4_0_1 {

    static public readonly new TypeInfo typeInfo = new TypeInfo("pdumodel.TypeBResidualCurrentNumericSensor:1.0.0", null);

    public TypeBResidualCurrentNumericSensor(Agent agent, string rid, TypeInfo ti) : base(agent, rid, ti) {}
    public TypeBResidualCurrentNumericSensor(Agent agent, string rid) : this(agent, rid, typeInfo) {}

    public static new TypeBResidualCurrentNumericSensor StaticCast(ObjectProxy proxy) {
      return proxy == null ? null : new TypeBResidualCurrentNumericSensor(proxy.Agent, proxy.Rid, proxy.StaticTypeInfo);
    }

    public class DegaussResult {
    }

    public DegaussResult degauss() {
      JsonObject _parameters = null;
      var _result = RpcCall("degauss", _parameters);
      var _ret = new DegaussResult();
      return _ret;
    }

    public AsyncRequest degauss(AsyncRpcResponse<DegaussResult>.SuccessHandler rsp, AsyncRpcResponse.FailureHandler fail) {
      return degauss(rsp, fail, RpcCtrl.Default);
    }

    public AsyncRequest degauss(AsyncRpcResponse<DegaussResult>.SuccessHandler rsp, AsyncRpcResponse.FailureHandler fail, RpcCtrl rpcCtrl) {
      JsonObject _parameters = null;
      return RpcCall("degauss", _parameters,
        _result => {
          try {
            var _ret = new DegaussResult();
            rsp(_ret);
          } catch (Exception e) {
            if (fail != null) fail(e);
          }
        }, fail, rpcCtrl);
    }

  }
}
