# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from ServerMonitor.idl.

use strict;

package Raritan::RPC::servermon::ServerMonitor_2_0_1::ServerPowerState;

use constant UNKNOWN => 0;
use constant ON => 1;
use constant OFF => 2;
use constant SHUTTING_DOWN => 3;

1;
