# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Webcam.idl.

use strict;

package Raritan::RPC::webcam::Controls;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'brightness'} = 1 * $in->{'brightness'};
    $encoded->{'contrast'} = 1 * $in->{'contrast'};
    $encoded->{'saturation'} = 1 * $in->{'saturation'};
    $encoded->{'gain'} = 1 * $in->{'gain'};
    $encoded->{'gamma'} = 1 * $in->{'gamma'};
    $encoded->{'powerLineFrequency'} = $in->{'powerLineFrequency'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'brightness'} = $in->{'brightness'};
    $decoded->{'contrast'} = $in->{'contrast'};
    $decoded->{'saturation'} = $in->{'saturation'};
    $decoded->{'gain'} = $in->{'gain'};
    $decoded->{'gamma'} = $in->{'gamma'};
    $decoded->{'powerLineFrequency'} = $in->{'powerLineFrequency'};
    return $decoded;
}

1;
