// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright 2020 Raritan Inc. All rights reserved.
//
// This file was generated by IdlC from Unit.idl.

using System;
using System.Linq;
using LightJson;
using Com.Raritan.Idl;
using Com.Raritan.JsonRpc;
using Com.Raritan.Util;

#pragma warning disable 0108, 0219, 0414, 1591

namespace Com.Raritan.JsonRpc.pdumodel.Unit_2_0_1 {
  public class IdentificationStartedEvent_ValObjCodec : Com.Raritan.JsonRpc._event.UserEvent_ValObjCodec {

    public static new void Register() {
      ValueObjectCodec.RegisterCodec(Com.Raritan.Idl.pdumodel.Unit_2_0_1.IdentificationStartedEvent.typeInfo, new IdentificationStartedEvent_ValObjCodec());
    }

    public override void EncodeValObj(LightJson.JsonObject json, ValueObject vo) {
      base.EncodeValObj(json, vo);
      var inst = (Com.Raritan.Idl.pdumodel.Unit_2_0_1.IdentificationStartedEvent)vo;
      json["duration"] = inst.duration;
    }

    public override ValueObject DecodeValObj(ValueObject vo, LightJson.JsonObject json, Agent agent) {
      Com.Raritan.Idl.pdumodel.Unit_2_0_1.IdentificationStartedEvent inst;
      if (vo == null) {
        inst = new Com.Raritan.Idl.pdumodel.Unit_2_0_1.IdentificationStartedEvent();
      } else {
        inst = (Com.Raritan.Idl.pdumodel.Unit_2_0_1.IdentificationStartedEvent)vo;
      }
      base.DecodeValObj(vo, json, agent);
      inst.duration = (int)json["duration"];
      return inst;
    }

  }
}
