# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from OverCurrentProtectors.idl.

use strict;

package Raritan::RPC::pdumodel::OverCurrentProtectors::Info;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'numberOfOCPs'} = 1 * $in->{'numberOfOCPs'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'numberOfOCPs'} = $in->{'numberOfOCPs'};
    return $decoded;
}

1;
