# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Sensor.idl.

use strict;

package Raritan::RPC::sensors::Sensor_3_0_0::Type;

use constant UNSPECIFIED => 0;
use constant VOLTAGE => 1;
use constant CURRENT => 2;
use constant UNBALANCE_CURRENT => 3;
use constant POWER => 4;
use constant POWER_FACTOR => 5;
use constant ENERGY => 6;
use constant FREQUENCY => 7;
use constant TEMPERATURE => 8;
use constant HUMIDITY => 9;
use constant AIR_FLOW => 10;
use constant AIR_PRESSURE => 11;
use constant CONTACT_CLOSURE => 12;
use constant ON_OFF_SENSOR => 13;
use constant TRIP_SENSOR => 14;
use constant VIBRATION => 15;
use constant WATER_LEAK => 16;
use constant SMOKE_DETECTOR => 17;
use constant TOTAL_HARMONIC_DISTORTION => 18;
use constant MASS => 19;
use constant ELECTRICAL_RESISTANCE => 20;
use constant FLUX => 21;
use constant LUMINOUS_INTENSITY => 22;
use constant ACCELERATION => 23;
use constant MAGNETIC_FLUX_DENSITY => 24;
use constant ELECTRIC_FIELD_STRENGTH => 25;
use constant MAGNETIC_FIELD_STRENGTH => 26;
use constant ANGLE => 27;
use constant SELECTION => 28;
use constant FAULT_STATE => 29;
use constant POWER_QUALITY => 30;
use constant ROTATIONAL_SPEED => 31;
use constant LUMINOUS_ENERGY => 32;
use constant LUMINOUS_FLUX => 33;
use constant ILLUMINANCE => 34;
use constant LUMINOUS_EMITTANCE => 35;

1;
