# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from AssetStrips.idl.

use strict;

package Raritan::RPC::assetmgrmodel::AssetStrips::Info;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'numberOfAssetStrips'} = 1 * $in->{'numberOfAssetStrips'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'numberOfAssetStrips'} = $in->{'numberOfAssetStrips'};
    return $decoded;
}

1;
