// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright 2020 Raritan Inc. All rights reserved.
//
// This file was generated by IdlC from BulkRequest.idl.

using System;
using System.Linq;
using LightJson;
using Com.Raritan.Idl;
using Com.Raritan.JsonRpc;
using Com.Raritan.Util;

#pragma warning disable 0108, 0219, 0414, 1591

namespace Com.Raritan.Idl.bulkrpc {

  public class Request : ICloneable {
    public object Clone() {
      Request copy = new Request();
      copy.rid = this.rid;
      copy.json = this.json;
      return copy;
    }

    public LightJson.JsonObject Encode() {
      LightJson.JsonObject json = new LightJson.JsonObject();
      json["rid"] = this.rid;
      json["json"] = this.json;
      return json;
    }

    public static Request Decode(LightJson.JsonObject json, Agent agent) {
      Request inst = new Request();
      inst.rid = (string)json["rid"];
      inst.json = (string)json["json"];
      return inst;
    }

    public string rid = "";
    public string json = "";
  }
}
