# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from PeripheralDeviceManager.idl.

use strict;

package Raritan::RPC::peripheral::DeviceManager_2_0_2::MetaData;

sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'oneWirePortCount'} = 1 * $in->{'oneWirePortCount'};
    $encoded->{'onboardDeviceCount'} = 1 * $in->{'onboardDeviceCount'};
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'oneWirePortCount'} = $in->{'oneWirePortCount'};
    $decoded->{'onboardDeviceCount'} = $in->{'onboardDeviceCount'};
    return $decoded;
}

1;
