# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from DiagLogSettings.idl.

use strict;

package Raritan::RPC::diag::DiagLogSettings::LogLevel;

use constant LOG_LEVEL_NONE => 0;
use constant LOG_LEVEL_ERR => 1;
use constant LOG_LEVEL_WARN => 2;
use constant LOG_LEVEL_INFO => 3;
use constant LOG_LEVEL_DEBUG => 4;
use constant LOG_LEVEL_TRACE => 5;

1;
