# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Port.idl.

use strict;

package Raritan::RPC::portsmodel::Port_2_0_2::DetectionType;

use constant AUTO => 0;
use constant PINNED => 1;
use constant DISABLED => 2;

1;
