# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from GsmModem.idl.

use strict;

package Raritan::RPC::serial::GsmModem_1_0_1::SimSecurityStatus;

use constant UNLOCKED => 0;
use constant WAITFORPIN => 1;
use constant WAITFORPUK => 2;
use constant UNKNOWN => 3;

1;
