# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from NumericSensor.idl.

use strict;

package Raritan::RPC::sensors::NumericSensor_4_0_2::ThresholdsChangedEvent;

use constant typeId => "sensors.NumericSensor_4_0_2.ThresholdsChangedEvent:1.0.0";
use Raritan::RPC::sensors::NumericSensor_4_0_2::Thresholds;
use Raritan::RPC::event::UserEvent;
use Raritan::RPC::sensors::NumericSensor_4_0_2::Thresholds;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::event::UserEvent::encode($in);
    $encoded->{'oldThresholds'} = Raritan::RPC::sensors::NumericSensor_4_0_2::Thresholds::encode($in->{'oldThresholds'});
    $encoded->{'newThresholds'} = Raritan::RPC::sensors::NumericSensor_4_0_2::Thresholds::encode($in->{'newThresholds'});
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::event::UserEvent::decode($agent, $in);
    $decoded->{'oldThresholds'} = Raritan::RPC::sensors::NumericSensor_4_0_2::Thresholds::decode($agent, $in->{'oldThresholds'});
    $decoded->{'newThresholds'} = Raritan::RPC::sensors::NumericSensor_4_0_2::Thresholds::decode($agent, $in->{'newThresholds'});
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('sensors.NumericSensor_4_0_2.ThresholdsChangedEvent', 1, 0, 0, 'Raritan::RPC::sensors::NumericSensor_4_0_2::ThresholdsChangedEvent');
1;
