# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from PowerQualitySensor.idl.

use strict;

package Raritan::RPC::pdumodel::PowerQualitySensor_2_0_1;

use parent qw(Raritan::RPC::sensors::StateSensor_4_0_1);

use constant typeId => "pdumodel.PowerQualitySensor:2.0.1";

sub new {
    my ($class, $agent, $rid, $typeId) = @_;
    $typeId = $typeId || Raritan::RPC::pdumodel::PowerQualitySensor_2_0_1::typeId;
    return $class->SUPER::new($agent, $rid, $typeId);
}

use constant STATE_NORMAL => 0;

use constant STATE_WARNING => 1;

use constant STATE_CRITICAL => 2;

Raritan::RPC::Registry::registerProxyClass('pdumodel.PowerQualitySensor', 2, 0, 1, 'Raritan::RPC::pdumodel::PowerQualitySensor_2_0_1');
1;
