# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Pole.idl.

use strict;

package Raritan::RPC::pdumodel::PowerLine;

use constant L1 => 0;
use constant L2 => 1;
use constant L3 => 2;
use constant NEUTRAL => 3;

1;
