# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Firmware.idl.

use strict;

package Raritan::RPC::firmware::SystemStartupEvent;

use constant typeId => "firmware.SystemStartupEvent:1.0.0";
use Raritan::RPC::idl::Event;

sub encode {
    my ($in) = @_;
    my $encoded = Raritan::RPC::idl::Event::encode($in);
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = Raritan::RPC::idl::Event::decode($agent, $in);
    return $decoded;
}

Raritan::RPC::Registry::registerCodecClass('firmware.SystemStartupEvent', 1, 0, 0, 'Raritan::RPC::firmware::SystemStartupEvent');
1;
