// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright 2020 Raritan Inc. All rights reserved.
//
// This file was generated by IdlC from SnmpV3.idl.

using System;
using System.Linq;
using LightJson;
using Com.Raritan.Idl;
using Com.Raritan.JsonRpc;
using Com.Raritan.Util;

#pragma warning disable 0108, 0219, 0414, 1591

namespace Com.Raritan.Idl.um {
  public class SnmpV3 : ObjectProxy {

    static public readonly new TypeInfo typeInfo = new TypeInfo("um.SnmpV3:1.0.0", null);

    public SnmpV3(Agent agent, string rid, TypeInfo ti) : base(agent, rid, ti) {}
    public SnmpV3(Agent agent, string rid) : this(agent, rid, typeInfo) {}

    public static new SnmpV3 StaticCast(ObjectProxy proxy) {
      return proxy == null ? null : new SnmpV3(proxy.Agent, proxy.Rid, proxy.StaticTypeInfo);
    }

    public enum SecurityLevel {
      NO_AUTH_NO_PRIV,
      AUTH_NO_PRIV,
      AUTH_PRIV,
    }

    public enum AuthProtocol {
      MD5,
      SHA1,
    }

    public enum PrivProtocol {
      DES,
      AES128,
    }

  }
}
