# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from Net.idl.

use strict;

package Raritan::RPC::net::InterfaceState;


sub encode {
    my ($in) = @_;
    my $encoded = {};
    $encoded->{'mode'} = $in->{'mode'};
    $encoded->{'wirelessSupported'} = ($in->{'wirelessSupported'}) ? JSON::true : JSON::false;
    return $encoded;
}

sub decode {
    my ($agent, $in) = @_;
    my $decoded = {};
    $decoded->{'mode'} = $in->{'mode'};
    $decoded->{'wirelessSupported'} = ($in->{'wirelessSupported'}) ? 1 : 0;
    return $decoded;
}

1;
