// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright 2020 Raritan Inc. All rights reserved.
//
// This file was generated by IdlC from Sensor.idl.

using System;
using System.Linq;
using LightJson;
using Com.Raritan.Idl;
using Com.Raritan.JsonRpc;
using Com.Raritan.Util;

#pragma warning disable 0108, 0219, 0414, 1591

namespace Com.Raritan.JsonRpc.sensors.Sensor_4_0_2 {
  public class TypeSpecChangedEvent_ValObjCodec : Com.Raritan.JsonRpc.idl.Event_ValObjCodec {

    public static new void Register() {
      ValueObjectCodec.RegisterCodec(Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpecChangedEvent.typeInfo, new TypeSpecChangedEvent_ValObjCodec());
    }

    public override void EncodeValObj(LightJson.JsonObject json, ValueObject vo) {
      base.EncodeValObj(json, vo);
      var inst = (Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpecChangedEvent)vo;
      json["oldTypeSpec"] = inst.oldTypeSpec.Encode();
      json["newTypeSpec"] = inst.newTypeSpec.Encode();
    }

    public override ValueObject DecodeValObj(ValueObject vo, LightJson.JsonObject json, Agent agent) {
      Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpecChangedEvent inst;
      if (vo == null) {
        inst = new Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpecChangedEvent();
      } else {
        inst = (Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpecChangedEvent)vo;
      }
      base.DecodeValObj(vo, json, agent);
      inst.oldTypeSpec = Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpec.Decode(json["oldTypeSpec"], agent);
      inst.newTypeSpec = Com.Raritan.Idl.sensors.Sensor_4_0_2.TypeSpec.Decode(json["newTypeSpec"], agent);
      return inst;
    }

  }
}
