# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from EventEngine.idl.

use strict;

package Raritan::RPC::event::Engine::Condition::Op;

use constant AND => 0;
use constant OR => 1;
use constant XOR => 2;

1;
