# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright 2020 Raritan Inc. All rights reserved.
#
# This file was generated by IdlC from OverCurrentProtector.idl.

use strict;

package Raritan::RPC::pdumodel::OverCurrentProtector_3_0_0::Type;

use constant BREAKER_1POLE => 0;
use constant BREAKER_2POLE => 1;
use constant BREAKER_3POLE => 2;
use constant FUSE => 3;
use constant FUSE_PAIR => 4;
use constant RCBO_2POLE => 5;
use constant RCBO_3POLE => 6;
use constant RCBO_4POLE => 7;

1;
